<?php
$games = [
    [
        'id' => 10,
        'name' => 'Dying Light 2',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi eos error fugit id, ipsum laboriosam laborum nostrum obcaecati pariatur perspiciatis, praesentium quia quidem quod quos rem rerum sapiente ullam voluptas.',
        'poster' => 'https://image.api.playstation.com/vulcan/img/rnd/202106/2908/7aJhOMuJALdBPqZHVy3CgJsg.png',
        'releaseDate' => '2022-02-04',
        'editor' => 'Techland',
        'developer' => 'Techland',
        'category' => '	Survival horror',
        'platforms' => ['Playstation 5', 'PC', 'XBox Series'],
        'reviews' => [7.5, 8, 4.3, 6],
    ],
    [
        'id' => 11,
        'name' => 'Minecraft',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi eos error fugit id, ipsum laboriosam laborum nostrum obcaecati pariatur perspiciatis, praesentium quia quidem quod quos rem rerum sapiente ullam voluptas.',
        'poster' => 'https://image.api.playstation.com/vulcan/img/cfn/11307x4B5WLoVoIUtdewG4uJ_YuDRTwBxQy0qP8ylgazLLc01PBxbsFG1pGOWmqhZsxnNkrU3GXbdXIowBAstzlrhtQ4LCI4.png',
        'releaseDate' => '2011-11-18',
        'editor' => 'Xbox Game Studios',
        'developer' => 'Mojang Studios',
        'category' => 'Bac à sable',
        'platforms' => ['PC', 'Nitendo Switch'],
        'reviews' => [8, 2.3, 6.9, 8.5],
    ],
    [
        'id' => 3,
        'name' => 'Escape Simulator',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi eos error fugit id, ipsum laboriosam laborum nostrum obcaecati pariatur perspiciatis, praesentium quia quidem quod quos rem rerum sapiente ullam voluptas.',
        'poster' => 'https://image.jeuxvideo.com/medias-crop-1200-675/163941/1639406520-6656-card.jpg',
        'releaseDate' => '2021-10-19',
        'editor' => 'Pine Studio',
        'developer' => 'Pine Studio',
        'category' => 'Enigme',
        'platforms' => ['PC'],
        'reviews' => [7.8, 6.2, 9.4],
    ],
    [
        'id' => 4,
        'name' => 'FIFA 22',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi eos error fugit id, ipsum laboriosam laborum nostrum obcaecati pariatur perspiciatis, praesentium quia quidem quod quos rem rerum sapiente ullam voluptas.',
        'poster' => 'https://image.api.playstation.com/vulcan/img/rnd/202111/0822/YiFF5Xkljek03HhUJa4gic1Y.png',
        'releaseDate' => '2021-11-01',
        'editor' => 'Electronic Arts',
        'developer' => 'Electronic Arts',
        'category' => 'Sport',
        'platforms' => ['PC', 'Playstation 5', 'XBox Series'],
        'reviews' => [2, 8],
    ],
];